<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="2" passed="0" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-07-28T12:25:47Z" name="Default suite" finished-at="2022-07-28T12:25:54Z" duration-ms="7461">
    <groups>
      <group name="TransactionManagerClientTest">
        <method signature="TransactionManagerClientTest.testPurchaseOrderProcess_OK()[pri:0, instance:com.dieboldnixdorf.sbt.trm.tests.TransactionManagerClientTest@289710d9]" name="testPurchaseOrderProcess_OK" class="com.dieboldnixdorf.sbt.trm.tests.TransactionManagerClientTest"/>
      </group> <!-- TransactionManagerClientTest -->
    </groups>
    <test started-at="2022-07-28T12:25:47Z" name="Default test" finished-at="2022-07-28T12:25:54Z" duration-ms="7461">
      <class name="com.dieboldnixdorf.sbt.trm.tests.TransactionManagerClientTest">
        <test-method is-config="true" signature="arquillianBeforeSuite()[pri:0, instance:com.dieboldnixdorf.sbt.trm.tests.TransactionManagerClientTest@289710d9]" started-at="2022-07-28T12:25:47Z" name="arquillianBeforeSuite" finished-at="2022-07-28T12:25:47Z" duration-ms="48" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arquillianBeforeSuite -->
        <test-method is-config="true" signature="arquillianBeforeClass()[pri:0, instance:com.dieboldnixdorf.sbt.trm.tests.TransactionManagerClientTest@289710d9]" started-at="2022-07-28T12:25:47Z" name="arquillianBeforeClass" finished-at="2022-07-28T12:25:48Z" duration-ms="1366" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arquillianBeforeClass -->
        <test-method is-config="true" signature="arquillianBeforeTest(java.lang.reflect.Method)[pri:0, instance:com.dieboldnixdorf.sbt.trm.tests.TransactionManagerClientTest@289710d9]" started-at="2022-07-28T12:25:48Z" name="arquillianBeforeTest" finished-at="2022-07-28T12:25:48Z" duration-ms="42" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.dieboldnixdorf.sbt.trm.tests.TransactionManagerClientTest.testPurchaseOrderProcess_OK() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arquillianBeforeTest -->
        <test-method is-config="true" signature="prepare()[pri:0, instance:com.dieboldnixdorf.sbt.trm.tests.TransactionManagerClientTest@289710d9]" started-at="2022-07-28T12:25:48Z" name="prepare" finished-at="2022-07-28T12:25:54Z" duration-ms="5943" status="FAIL">
          <exception class="org.apache.http.conn.HttpHostConnectException">
            <message>
              <![CDATA[Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
at com.dieboldnixdorf.txm.uc.internal.communication.ServerInvocation.invokeServerCall(ServerInvocation.java:32)
at com.dieboldnixdorf.txm.uc.internal.communication.ServerConnectionImpl.callServer(ServerConnectionImpl.java:96)
at com.dieboldnixdorf.txm.uc.internal.initialize.Initializer.lambda$initClientWithServerCall$4(Initializer.java:153)
at com.dieboldnixdorf.txm.core.internal.util.Uncheck.uncheck(Uncheck.java:102)
at com.dieboldnixdorf.txm.uc.internal.initialize.Initializer.initClientWithServerCall(Initializer.java:143)
at com.dieboldnixdorf.txm.uc.internal.initialize.Initializer.doInitOnline(Initializer.java:115)
at com.dieboldnixdorf.txm.uc.internal.initialize.Initializer.initialize(Initializer.java:72)
at com.dieboldnixdorf.txm.uc.internal.initialize.FactoryImpl.getServerContext(FactoryImpl.java:57)
at com.dieboldnixdorf.txm.uc.communication.ConnectionFactory.getServerContext(ConnectionFactory.java:53)
at com.dieboldnixdorf.sbt.trm.tests.TransactionManagerClientTest.prepare(TransactionManagerClientTest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.net.ConnectException: Connection refused: connect
at java.base/sun.nio.ch.Net.connect0(Native Method)
at java.base/sun.nio.ch.Net.connect(Net.java:579)
at java.base/sun.nio.ch.Net.connect(Net.java:568)
at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
at java.base/java.net.Socket.connect(Socket.java:633)
at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
... 48 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.http.conn.HttpHostConnectException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- prepare -->
        <test-method signature="testPurchaseOrderProcess_OK()[pri:0, instance:com.dieboldnixdorf.sbt.trm.tests.TransactionManagerClientTest@289710d9]" started-at="2022-07-28T12:25:54Z" name="testPurchaseOrderProcess_OK" finished-at="2022-07-28T12:25:54Z" duration-ms="0" status="SKIP">
          <exception class="org.apache.http.conn.HttpHostConnectException">
            <message>
              <![CDATA[Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
at com.dieboldnixdorf.txm.uc.internal.communication.ServerInvocation.invokeServerCall(ServerInvocation.java:32)
at com.dieboldnixdorf.txm.uc.internal.communication.ServerConnectionImpl.callServer(ServerConnectionImpl.java:96)
at com.dieboldnixdorf.txm.uc.internal.initialize.Initializer.lambda$initClientWithServerCall$4(Initializer.java:153)
at com.dieboldnixdorf.txm.core.internal.util.Uncheck.uncheck(Uncheck.java:102)
at com.dieboldnixdorf.txm.uc.internal.initialize.Initializer.initClientWithServerCall(Initializer.java:143)
at com.dieboldnixdorf.txm.uc.internal.initialize.Initializer.doInitOnline(Initializer.java:115)
at com.dieboldnixdorf.txm.uc.internal.initialize.Initializer.initialize(Initializer.java:72)
at com.dieboldnixdorf.txm.uc.internal.initialize.FactoryImpl.getServerContext(FactoryImpl.java:57)
at com.dieboldnixdorf.txm.uc.communication.ConnectionFactory.getServerContext(ConnectionFactory.java:53)
at com.dieboldnixdorf.sbt.trm.tests.TransactionManagerClientTest.prepare(TransactionManagerClientTest.java:38)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.net.ConnectException: Connection refused: connect
at java.base/sun.nio.ch.Net.connect0(Native Method)
at java.base/sun.nio.ch.Net.connect(Net.java:579)
at java.base/sun.nio.ch.Net.connect(Net.java:568)
at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
at java.base/java.net.Socket.connect(Socket.java:633)
at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
... 48 more
]]>
            </full-stacktrace>
          </exception> <!-- org.apache.http.conn.HttpHostConnectException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPurchaseOrderProcess_OK -->
        <test-method is-config="true" signature="arquillianAfterTest(java.lang.reflect.Method)[pri:0, instance:com.dieboldnixdorf.sbt.trm.tests.TransactionManagerClientTest@289710d9]" started-at="2022-07-28T12:25:54Z" name="arquillianAfterTest" finished-at="2022-07-28T12:25:54Z" duration-ms="5" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.dieboldnixdorf.sbt.trm.tests.TransactionManagerClientTest.testPurchaseOrderProcess_OK() throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arquillianAfterTest -->
        <test-method is-config="true" signature="arquillianAfterClass()[pri:0, instance:com.dieboldnixdorf.sbt.trm.tests.TransactionManagerClientTest@289710d9]" started-at="2022-07-28T12:25:54Z" name="arquillianAfterClass" finished-at="2022-07-28T12:25:54Z" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arquillianAfterClass -->
        <test-method is-config="true" signature="arquillianAfterSuite()[pri:0, instance:com.dieboldnixdorf.sbt.trm.tests.TransactionManagerClientTest@289710d9]" started-at="2022-07-28T12:25:54Z" name="arquillianAfterSuite" finished-at="2022-07-28T12:25:54Z" duration-ms="3" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- arquillianAfterSuite -->
      </class> <!-- com.dieboldnixdorf.sbt.trm.tests.TransactionManagerClientTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
